services:
  - type: web
    name: jeju-quest-landing
    env: python
    rootDir: project
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com

databases:
  - name: jeju-quest-db
    databaseName: jeju_quest
    user: jeju_quest_user
